# Generated by Django 4.2.4 on 2023-08-19 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("responder", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tgmessages",
            name="chat_id",
        ),
        migrations.AlterField(
            model_name="tgmessages",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name="ChatIdList",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("chat_id", models.IntegerField()),
                ("first_msg_token", models.CharField(max_length=50)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
