# Generated by Django 4.2.4 on 2023-08-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("responder", "0002_remove_tgmessages_chat_id_alter_tgmessages_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatidlist",
            name="chat_id",
            field=models.BigIntegerField(),
        ),
    ]
